name = "scope/scope"
version = "0.1.0"
license = "MIT"

[target]
environment = "roblox"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
uilabs = { wally = "pepeeltoro41/ui-labs", version = "2.4.0" }

[dependencies]
promise = { wally = "howmanysmall/typed-promise", version = "^4.0.6" }
profile_store = { wally = "lm-loleris/profilestore", version = "^1.0.3" }
conch = { wally = "alicesaidhi/conch", version = "^0.3.0" }
conch-ui = { wally = "alicesaidhi/conch-ui", version = "^0.3.0" }
