[tools]
rojo = "rojo-rbx/rojo@7.5.1"
pesde = "pesde-pkg/pesde@0.7.0+registry.0.2.3"
lune = "lune-org/lune@0.8.9"
just = "casey/just@1.42.4"
blink = "1Axen/blink@0.18.1"
darklua = "seaofvoices/darklua@0.17.1"
asphalt = "jackTabsCode/asphalt@0.9.1"
styLua = "JohnnyMorganz/StyLua@2.1.0"
selene = "Kampfkarren/selene@0.29.0"
